# Generated by Django 4.0.6 on 2022-08-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_partner_is_published_alter_partner_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='uploads/partners/logotypes', verbose_name='Логотип'),
        ),
    ]
