# Generated by Django 4.0.6 on 2022-08-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_partner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partners/logotypes/', verbose_name='Логотип'),
        ),
    ]
