# Generated by Django 4.0.6 on 2022-08-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='img',
            field=models.ImageField(upload_to='review', verbose_name='Фото'),
        ),
    ]
